Petitions/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'

  get 'petitions/index'

  get 'users/index'

  resources :users, :sessions, :petitions
  root to: 'petitions#index'

end

Petitions/app/models/petition.rb
class Petition < ActiveRecord::Base
  EXPIRATION_DAYS = 30
  NEEDED_VOTES = 100

  belongs_to :user

  has_many :votes

  scope :expired, -> { where('DATE(created_at) < ?', EXPIRATION_DAYS.days.ago) }

  validate :validate_petition_is_not_expired, on: :update

  def validate_petition_is_not_expired
    errors.add(:base, I18n.t('petition.errors.expired')) if expired?
  end

  def expired?
    created_at < EXPIRATION_DAYS.days.ago
  end

  def collected_votes?
    votes.count >= NEEDED_VOTES
  end

  def days_left
    return 0 if expired?
    (created_at + EXPIRATION_DAYS.days - Time.now).divmod(60*60*24)[0]
  end

  def voted_by?(user)
    votes.where(user_id: user.id).any?
  end

  def owner?(other_user)
    user == other_user
  end
end

Petitions/app/models/petitions.rb
class Petitions < ActiveRecord::Base


  belongs_to :user

  validates :title,  :presence => true,
            :uniqueness => true,
            :length => {:minimum => 1}

  validates :text, :presence => true,
            :length => {:minimum => 1},
            :uniqueness => true
end

Petitions/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :petitions
  has_many :votes

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def name
    "#{first_name} #{last_name}"
  end
end

Petitions/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :petition

  validates :user_id, uniqueness: { scope: :petition_id}
  validate :validate_petition_is_not_expired, on: :create

  def validate_petition_is_not_expired
    errors.add(:base, I18n.t('petition.errors.expired')) if petition.expired?
  end
end
Status API Training Shop Blog About

Petitions/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: 'Вы не авторизованы' if current_user.nil?
  end
end

Petitions/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @petitions = Petition.order(created_at: :desc).limit(10)
  end
end

Petitions/app/controllers/petitions_controller.rb
class PetitionsController < ApplicationController
  before_action :authorize, only: [:new, :create]

  def index
    @petitions = Petition.all
    if params[:my]
      @petitions = @petitions.where(user: current_user)
      render 'my_index'
    end
  end

  def show
    @petition = Petition.find(params[:id])
  end

  def create
    petition = current_user.petitions.create(permitted_params)
    redirect_to petition
  end

  def new
    @petition = current_user.petitions.new
  end

  def edit
    @petition = current_user.petitions.find(params[:id])
  end

  def update
    petition = current_user.petitions.find(params[:id])
    petition.update!(permitted_params)
    redirect_to petition, notice: 'Петиция обновлена'
  end

  def destroy
    petition = current_user.petitions.find(params[:id])
    petition.destroy
    redirect_to action: :index, notice: 'Петиция удалена'
  end

  private

  def permitted_params
    params.require(:petition).permit(:title, :description)
  end
end

Petitions/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Добро пожаловать!'
    else
      flash.now.alert = 'Email или пароль не верный'
      render "new"
    end
  end

Petitions/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(permitted_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Добро пожаловать!'
    else
      render 'new'
    end
  end

Petitions/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authorize

  def create
    vote = current_user.votes.create(permitted_params)
    redirect_to vote.petition, notice: 'Спасибо! Ваш голос учтен'
  end

  def permitted_params
    params.permit(:petition_id)
  end
end

Petitions/app/helpers/petitions_helper.rb
module PetitionsHelper
end

Petitions/app/helpers/sessions_helper.rb
module SessionsHelper
end

Petitions/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

Petitions/app/helpers/users_helper.rb
module UsersHelper
end

Petitions/app/views/home/index.html.erb
<h2>Последние петиции</h2>

<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
    <th>Голоса</th>
    <th>Осталось дней</th>
    <th>Дата создания</th>
  </tr>
  </thead>
  <% @petitions.each do |petition| %>
      <%= render 'petitions/petition', petition: petition %>
  <% end %>
</table>

Petitions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Петиции" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Онлайн петиции нашего района</a>
    <div class="pull-right" style="margin: 10px">
          <span >
          <% if current_user %>
            <%= current_user.email %>
                (<%= link_to "Выйти", logout_path %>)
          <% else %>
            <%= link_to "Зарегистироваться", signup_path %> |
                <%= link_to "Войти", login_path %>
          <% end %>
          </span>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
    <div class="col-lg-3">
      <div class="well sidebar-nav">
        <ul class="nav nav-list la">
          <li><h4><%= link_to "Все петиции", petitions_path  %></h4></li>
          <li><h4><%= link_to "Создать петицию", new_petition_path  %></h4></li>
          <% if current_user %>
              <li><h4><%= link_to "Мои петиции", petitions_path(my: true)  %></h4></li>
          <% end %>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
  </div><!--/row-->

  <footer>
    <p>&copy; Company 2016</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

Petitions/app/views/petitions/_form.html.erb
<%= form_for @petition do |f| %>
    <% if @petition.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @petition.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :title, 'Название' %><br />
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :description, 'Описание' %><br />
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class="actions">
      <%= submit_tag @petition.new_record? ? 'Cоздать' : 'Сохранить', class: 'btn btn-success' %>
    </div>
<% end %>

Petitions/app/views/petitions/_my_petition.html.erb
<tr>
  <td><%= link_to petition.title, petition_path(petition) %></td>
  <td><%= petition.votes.count %></td>
  <td><%= petition.created_at.strftime('%d/%m/%Y %H:%M') %></td>
  <td><%= link_to 'Изменить', edit_petition_path(petition) %></td>
  <td><%= link_to 'Удалить', petition, method: :delete, data: { confirm: 'Вы уверенны?' }  %></td>
</tr>

Petitions/app/views/petitions/_petition.html.erb
<tr>
  <td><%= link_to petition.title, petition_path(petition) %></td>
  <td><%= petition.user.name %></td>
  <td><%= petition.votes.count %></td>
  <td><%= petition.created_at.strftime('%d/%m/%Y %H:%M') %></td>
</tr>

Petitions/app/views/petitions/edit.html.erb
<h2>Изменение Петиции</h2>

<%= render 'form' %>

Petitions/app/views/petitions/index.html.erb
<h1>Все петиции </h1>

<div>
  <% flash.each do |name, msg| %>
      <%= msg %>
  <% end %>
</div>

<%= link_to 'Выйти', logout_path%>
<%= link_to 'Зарегистрироваться',signup_path %>
<%= link_to 'Войти', login_path %>

Petitions/app/views/petitions/my_index.html.erb
<h2>Мои петиции</h2>

<table class="table">
  <thead>
  <tr>
    <th>Петиция</th>
    <th>Голоса</th>
    <th>Дата создания</th>
    <th colspan="2" class="text-center">Действия</th>
  </tr>
  </thead>
  <% @petitions.each do |petition| %>
      <%= render 'my_petition', petition: petition %>
  <% end %>
</table>

Petitions/app/views/petitions/new.html.erb
<h2>Новая Петиция</h2>

<%= render 'form' %>

Petitions/app/views/petitions/show.html.erb
<h2>Петиция</h2>

<h3><%= @petition.title %></h3>

<p>
  <%= @petition.created_at.strftime('%d/%m/%Y %H:%M')  %>
</p>

<p>
  <%= @petition.description %>
</p>

<p>
  <b>Голосов:</b>
  <%= @petition.votes.count %>
</p>

<p>
  <% if @petition.voted_by?(current_user) %>
      Вы уже проголосовали за данную петицию
  <% else %>
      <%= button_to('Поддержать', votes_path({ petition_id: @petition.id }) ) %>
  <% end %>
</p>

Petitions/app/views/petitions/ten.html.erb
<h1>Последние петиции</h1>
<table>
  <tr>
    <th>Петиция</th>
    <th>Автор</th>
  </tr>

  <% @petitions.each do |petition| %>
      <tr>
        <td><%= petition.title %></td>
        <td><%= petition.author %></td>
        <td><%= link_to 'Просмотр', petition_path(petition) %></td>
      </tr>
  <% end %>
</table>

Petitions/app/views/users/new.html.erb
<h1>Регистрация</h1>

<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group" style="width: 50%">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :first_name, 'Имя'%><br />
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :last_name, "Фамилия" %><br />
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :password, 'Пароль' %><br />
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group" style="width: 50%">
      <%= f.label :password_confirmation, 'Подтверждение пароля' %><br />
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="actions"><%= f.submit "Зарегистрироваться", class: 'btn btn-primary' %></div>
<% end %>